biddr_api/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get("/",{to: "welcome#index", as: :root}) 
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :auctions do
    resources :bids, shallow: true, only: :create
  end
  namespace :api, defaults: { format: :json } do 
    namespace :v1 do 
      resources :auctions
      resource :session, only: [:create, :destroy]
      resource :users, only: [:create]
    end
  end

end

biddr_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

biddr_api/app/models/auction.rb
class Auction < ApplicationRecord
    #Associations
    belongs_to :user
    has_many :bids, dependent: :destroy
    #validations
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 5}
    validates :end_date, presence: true
    validates :reserve_price, numericality: {greater_than: 0}
end

biddr_api/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user
  validates :price, numericality: {greater_than: 0}

end

biddr_api/app/models/user.rb
class User < ApplicationRecord
    #Associations
    has_many :auctionss, dependent: :nullify
    has_many :bids, dependent: :nullify

    has_secure_password
    def full_name
        "#{first_name} #{last_name}"
    end
end

biddr_api/app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
    skip_before_action(:verify_authenticity_token)

    private

    def authenticate_user!
        render(
            json: {errors: 'You are not logged in'},
            status: 422
        ) unless user_signed_in?
    end

end

biddr_api/app/controllers/api/v1/auctions_controller.rb
class Api::V1::AuctionsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_auction, only: [:show]

    def new
    end
    def create 
        auction = Auction.new auction_params 
        auction.user = current_user 
        if auction.save 
            render json: { id: auction.id }
        else 
            render(
                json: { errors: auction.errors }, 
                status: 422 # Unprocessable Entity
            )
        end
    end
    def index
        auctions = Auction.order(created_at: :DESC)
        # render json: auctions
        render json: auctions, each_serializer: AuctionCollectionSerializer 

    end
    def show 
        @auction = Auction.find params[:id]
        render(
            json: @auction
        )
    end

    private

    def find_auction
        @auction = Auction.find params[:id]
    end

    def auction_params
        params.require(:auction).permit(:title, :body, :reserve_price, :end_date)
    end
end

biddr_api/app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::ApplicationController
    def create
        user=User.find_by(email: params[:email])
        if user&.authenticate(params[:password])
            session[:user_id]=user.id
            render json:{id: user.id}
        else
            render(
                json: {status: 404},
                status: 404
            )
        end
    end
    def get_current_user
        render json: current_user
    end
    def destroy
        session[:user_id]=nil
        render(
            json: {logged_out: true},
            status: 200
        )
    end
end

biddr_api/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApplicationController
    def create
        user=User.new params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation
        )
        if user.save
            session[:user_id]=user.id
            render(json: {id: user.id})
        else
            render(
                json:{errors:user.errors},
                status:422
            )
        end
    end 
end

biddr_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method(:current_user)
    # The method 'helper_method' is to explicitly share some methods defined in the controller to make them available for the views. This is used for any method that you need to access from both controllers and views.

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, notice: 'Please sign in' unless user_signed_in?
    end
end

biddr_api/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :auction_params, only: [:create]
    before_action :find_auction, only: [:show]
    def index
        @auctions = Auction.all.order(created_at: :DESC)
        respond_to do |format|
            format.html { render :index }
            format.json { render json: @auctions }
        end
    end
    def show
        # @auction = Auction.find params[:id]
        @bid = Bid.new
        @bids = @auction.bids.order(price: :DESC)
    end
    def new
        @auction = Auction.new
    end
    def create
        @auction =Auction.new auction_params
        @auction.user = current_user
        if @auction.save
            flash[:notice] = 'Auction Created Successfully'
            redirect_to auction_path(@auction)
        else
            render :new
        end
    end
    private
    def auction_params
        params.require(:auction).permit(:title, :body, :end_date, :reserve_price)
    end
    def find_auction
        @auction=Auction.find params[:id]
    end


end

biddr_api/app/controllers/bids_controller.rb
class BidsController < ApplicationController
    before_action :authenticate_user!
    before_action :bid_params, only: [:create]
    def create
        @auction = Auction.find params[:auction_id]
        @bid = Bid.new bid_params
        @bid.user = current_user
        @bid.auction = @auction
        if @bid.save
            redirect_to auction_path(@auction)
        else
            @bids = @auction.bids.order(price: :DESC)
            render 'auctions/show'    
        end 
    end

    private

    def bid_params
        params.require(:bid).permit(:price, :created_at)
    end
end

biddr_api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
        def new
        end
        def create
            @user = User.find_by_email params[:email]
            if  @user && @user.authenticate(params[:password])
                # authenticate is a method created by has_secure_password in a User model behind the scene
                # this mehtod takes the password convert it in to an encrypted hash in a same manner as it did while signing up user, and then compare it with password digest in a db. it will return true in case the hash is matched else false.
    
                session[:user_id]=@user.id
                # The 👆🏻'session' is an object usable in a controller that uses cookies to store encrypted data.
                # To sign in a user, we wstore their user_id in the session for later use or retreival
                redirect_to root_path, notice: 'Logged in'
            else
                flash[:alert]= 'Wrong email or password.'
                render :new
            end
    
        end
        def destroy
            session[:user_id]=nil
            redirect_to root_path, notice: 'Logged Out!'
        end
    
end

biddr_api/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :user_params, only: [:create]
    def new
        @user=User.new
    end
    def create
        @user=User.new user_params
        if @user.save
            session[:user_id]=@user.id
            redirect_to root_path, notice: "Logged in!"
        else
            render :new
        end
    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

biddr_api/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

biddr_api/app/helpers/application_helper.rb
module ApplicationHelper
end

biddr_api/app/helpers/sessions_helper.rb
module SessionsHelper
end

biddr_api/app/helpers/users_helper.rb
module UsersHelper
end

biddr_api/app/helpers/welcome_helper.rb
module WelcomeHelper
end

biddr_api/app/views/auctions/index.html.erb
<h1>Auctions</h1>
<% @auctions.each do |auction| %>
<div>
    <h2><%=link_to( auction.title, auction_path(auction.id)) %></h2>
    <p>Posted on<%= auction.created_at %></p>
</div>
<% end%>

biddr_api/app/views/auctions/new.html.erb
<h1>New Auction Item</h1>
<%= form_with model: @auction, local: true do |form|%>
    <% if @auction.errors.any? %>
        <ul>
            <% @auction.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <div>
        <%= form.label :title%><br>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body, cols: 50, rows:5%>
    </div>
    <div>
        <%= form.label :end_date %><br>
        <%= form.date_field :end_date, as: :end_date, value: form.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
    </div>
    <div>
        <%= form.label :reserve_price %><br>
        <%= form.text_field :reserve_price %>
        
    </div>
    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>

biddr_api/app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>
<p><%= @auction.body %></p>
<p>Current Price: $ <%= @auction.reserve_price %></p>
<p>Ends at: <%= @auction.end_date %></p>
<small>posted:
    <%= time_ago_in_words(@auction.created_at)  %> ago,
</small>
<small>Updated : <%= time_ago_in_words(@auction.updated_at)  %> ago</small>
<small>
<br>
<h3>Start Bidding:</h3>
<%= form_with model: [@auction, @bid], local: true do |f| %>
    <% if @bid.errors.present? %>
        <p class="form-errors">
            <%= @bid.errors.full_messages.join(", ") %>
        </p>
    <% end %>

    <div >
        <%= f.text_field(
            :price,
            cols: 50,
            rows: 3,
            placeholder:"enter your bid"
            
        ) %>
    </div><br>
    
    <%= f.submit 'bid' %>
<% end %>
<h3>Previous Bids:</h3>
<% if @bids.all.length != 0 %>
    <% @bids.each do |bid| %>
    <p>$<%=bid.price%> on <%= bid.created_at %></p>
    <% end %>
<% else %>
    <p>No bid </p>
<% end %>

biddr_api/app/views/layouts/_navbar.html.erb
<nav>
    
    <%= link_to 'Auctions', auctions_path %>
    <%= link_to 'New Auction Item', new_auction_path %>
    <% if user_signed_in? %>
        <span>Hello, <%= current_user.first_name %>!</span>
    
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: "Are you sure you want to log out?"} %>
  <% else %>
        <%= link_to "Login", new_session_path %>
        <%= link_to "Sign Up", new_user_path %>
  <% end %>
</nav>

biddr_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiddrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='container'>
  <%= render 'layouts/navbar'%>
  <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </body>
</html>

biddr_api/app/views/users/new.html.erb
<h1>Please sign up</h1>

<%= form_with model: @user, local: true do |f| %>
    <% if @user.errors.any? %>
        <p>
        <%= @user.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :email%>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit "Sign Up" %>

<% end %>

biddr_api/app/views/welcome/index.html.erb
<h1>Welcome to Auction-Bidder App</h1>